language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "0.6"
  - "iojs"
script:
  - npm test
secure:
  env:
    clientId: nBFgc6r70YXr7dElmWZeU701hMrWr8F3b9kVGXITFWGQ6JquXg07Rq9fN/gcQ04/BcIG2XD5Qg/12Zd/dCPY+Yv7f8813ZfYEQFztPaih35cv6seRBQmWWppUVYsWJ6geNv/Z+y1QO/4Da5UjpFV82U2fU4xAPrlfMEJgmM+9B9YJF0piMX2YbNe6ErQYsMjh6VmlGlgkFvBfpHTMOfCzIqk1kOT5Seh2EE4vsJ9eRee6qiJymvBaUKZegVOe0/vY8CBNksVw1VPGRnvZitihgCtS8ixPux9GWjp+q60OxLFn7sKSanPAZsjrTG+HygvOj/VsQkCiLWpxuQt01BZvAFs3enkonziy/PeEm2NNSxyw2bVaLb6N+InQAXj4m5wBq3ol5jFlGLAod9F2eUK43HQ/95ZiBu7n3jXjjZzV6/YnNA4Zd3vrCD/OuTAnsaChUQQPlDL33nL9/1GyYAPiee1dPd9DWAiNtZqMIAZbrSYGEbgIxwJyAa37jJpPPjRUp7h7giiqhjVKBr4yyWXc20+M5RqFg2163Kc9PvOrtNdb1GNnObTezgtLBreUIe66J6aPB5YC4Xv1s4sF1YIjC1l725WVWmY8MiTvjUfZ/PbdxhmpzVbfHzZ/lNEZz2HpvSLoWEA7XUTFatg8Dnw09d+DTb1k3SgxiYULXwnFNY=
    clientSecret: VX/P+6YcuLdhb/afj/ADsfsy0SKqHCfHdKwm1XgKheEumHI7hCVvZPPKH0hSed3BJ1Ta7oFhtHTTGN3aXVr/gOVPfiMFNZi7dBeM+Q9J527U1cTzoYCBmvDP34CWi38LDTUmB3YkgPC8oLGArDkhBhhqlYOwHR30UKDNbvrSgSlvD3vs4GbFCDL/8u2Sm9PeA8pu+TEl6dJKYMWrjiuEC8eStQJZsroJOUbZv9K0WjLbEZt+belPUnZ0KZq57i8Jb0104s09v/1dGoH0gw5YWVsZjGL/eTFOCHXRurg/4wisTqAA6MTUBBbgf+8/UhZm0RaNWqvoPL7RiCRhNSVGxCJ958vo+l9HAbnmCQ0ySDbdM39Sip4TiS24ttohrsPlo0WZw5x+ADyTKaGja3zUSkcwn5F52gDFz6C3yNSMgfpaQ4PBw5bsH5I5pJVV2tfoILNisU8UF2nXPCRjuNYgWNwhMP+1y9zPIUhaBmwkCBbbh0J/wiDJ097F27SmdUIQb0yxhH0MmCQu0j3lvX9PTFjA6DfJgdZh4EnOUQ9XOS8fW7RIizLh7YstosUwb06u9sVpHGS4/3JUBEhu09T6bWbabgpl04R745ZQdhmXwVPapSK8L+iwQCzb88jfrAFbJjgE5I0GolkRpffHamdk6lHf/tJcryUBtgBLOM2DNL0=
